Api/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from Api.views import UserLoginWeb, BlogListView, BlogDetailView, BlogAddView, BlogTypeView, BlogDateView, BlogSearchView


urlpatterns = [
    path('user/login', UserLoginWeb.as_view()),
    path('blog/', BlogListView.as_view()),                  # 文章列表
    path('blog/<int:id>', BlogDetailView.as_view()),        # 文章详情
    path('blog/type/<int:id>', BlogTypeView.as_view()),     # 分类查询
    path('blog/date/<int:year>', BlogDateView.as_view()),   # 年份查询
    path('blog/', BlogAddView.as_view()),

    path('blog/search', BlogSearchView.as_view()),
]

blog/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericRelation
from ckeditor_uploader.fields import RichTextUploadingField
from read_statistics.utils import ReadNumExpand, ReadNumDay

# Create your models here.


class BlogType(models.Model):
    '''
    类型表
    '''
    type_name = models.CharField(max_length=15)

    def __str__(self):
        return self.type_name

    class Meta:
        verbose_name = '类型'
        verbose_name_plural = '类型'


class Blog(models.Model, ReadNumExpand):
    '''
    博文表
    '''
    title = models.CharField(max_length=50)
    content = RichTextUploadingField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    create_time = models.DateTimeField(auto_now_add=True)
    last_update_time = models.DateTimeField(auto_now=True)

    # 外键与 类型表 相关联，多对一模式：(采用的是一种类型对应多篇博文)
    blog_type = models.ForeignKey(BlogType, on_delete=models.CASCADE)

    # 使用contenttype的GenericRelation进行反向链接，链接到每日阅读表中
    read_day_key = GenericRelation(ReadNumDay)

    def get_url(self):
        return reverse('blog_detail', kwargs={'blog_id': self.id})

    def get_email(self):
        return self.user.email

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-create_time']
        verbose_name = '博客'
        verbose_name_plural = '博客'

templates/blog_base.html
{% load notifications_tags %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static '/css/blog_base.css' %}">
    {% block css %}{% endblock %}
    <script src="{% static '/js/jquery-1-12-4.js' %}"></script>
    <script type="text/javascript" src="{% static '/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'notifications/notify.js' %}"></script>
    {% block js %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">欢迎来到网站</a>
                {# 小屏幕：下拉框 #}
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="{% block home_active %}{% endblock %}"><a href="/">首页</a></li>
                    <li class="{% block blog_active %}{% endblock %}"><a href="{% url 'blog_list' %}">博文</a></li>
                </ul>
                {# 用户 #}
                <ul class="nav navbar-nav navbar-right">
                    {% notifications_unread as unread_count %}
                    {% if user.is_authenticated %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">
                                <i class="unread"></i>
                                {{ user.username }}({{ user.nickname }})<span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'user_info' %}">个人资料</a></li>
                                <li>
                                    <a href="{% url 'notification' %}">
                                        消息通知
                                        <b class="unread_count live_notify_badge"></b>
                                    </a>
                                </li>
                                {% if user.is_staff or user.is_superuser %}
                                    <li><a href="{% url 'admin:index' %}">后台管理</a></li>
                                {% endif %}
                                <li><a href="{% url 'modify_password' %}">修改密码</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="{% url 'logout' %}">登出</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li><a href="{% url 'login_web' %}?from={{ request.get_full_path }}">登录</a></li>
                        <li><a href="{% url 'register' %}?from={{ request.get_full_path }}">注册</a></li>
                    {% endif %}

                    <form class="navbar-form navbar-left search-form" action="{% url 'search' %}">
                        <div class="form-group">
                            <input type="text" class="form-control" name="wd" placeholder="多词搜索用空格隔开">
                        </div>
                        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
                    </form>
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}{% endblock %}
    {# 弹出登录框 #}
    <div class="modal fade" id="login_modal_div" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">登录</h4>
                </div>
                <form id="login_modal" method="POST">
                    {% csrf_token %}
                    <div class="modal-body">
                        {%  for field in login_form %}
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            {{ field }}
                        {% endfor %}
                    </div>
                    <div class="modal-footer">
                        <span id="login_message" class="pull-left text-danger"></span>
                        <button type="submit" class="btn btn-primary">登录</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% block script %}{% endblock %}
    <script type="text/javascript">
        // 登录提交
        $('#login_modal').submit(function(event) {
            event.preventDefault();
            $.ajax({
                url: "{% url 'login_modal' %}",
                type: 'POST',
                data: $(this).serialize(),
                cache: false,
                success: function(data) {
                    if(data['status']== 200) {
                        window.location.reload()
                    }else{
                        $('#login_message').text('用户名或密码错误!!!');
                    }
                }
            });
        });
        function notification_callback(data){
            var unread_count = data['unread_count'];
            if (unread_count > 0){
                $('.unread').text('●');
                $('.live_notify_badge').text(unread_count)
            }
        }
    </script>
    {# 加载请求，并将消息数量填写到指定位置 #}
    {% register_notify_callbacks callbacks='notification_callback' %}
</body>
</html>

templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ERROR</title>
</head>
<body>
{{ message }}
</body>
</html>

templates/home.html
{% extends 'blog_base.html' %}
{% load staticfiles %}

{% block title %}
    我的网站|首页
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static '/css/home.css' %}">
{% endblock %}
{% block js %}
    <script type="text/javascript" src="https://code.highcharts.com.cn/highcharts/highcharts.js"></script>
{% endblock %}

{% block home_active %}
    active
{% endblock %}

{% block content %}
    <h2 class="text_content">欢迎来到网站</h2>
    <div id="container"></div>

    <div class="container">
        <div class="row">

            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                <div class="panel panel-default">
                    <div class="panel-heading">今日热读博文</div>
                    <div class="panel-body">
                        <ul>
                            {% for blog in today_hot_blog %}
                                <li><a href="{% url 'blog_detail' blog.id %}">{{ blog.title }}</a></li>
                            {% empty %}
                                <li>暂无热读博文</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>

            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                <div class="panel panel-default">
                    <div class="panel-heading">前7天热读博文</div>
                    <div class="panel-body">
                        <ul>
                            {% for blog in week_hot_blog %}
                                <li><a href="{% url 'blog_detail' blog.id %}">{{ blog.title }}</a></li>
                            {% empty %}
                                <li>暂无热读博文</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>

            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                <div class="panel panel-default">
                    <div class="panel-heading">前1月热读博文</div>
                    <div class="panel-body">
                        <ul>
                            {% for blog in month_hot_blog %}
                                <li><a href="{% url 'blog_detail' blog.id %}">{{ blog.title }}</a></li>
                            {% empty %}
                                <li>暂无热读博文</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>

            <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                <div class="panel panel-default">
                    <div class="panel-heading">前1年热读博文</div>
                    <div class="panel-body">
                        <ul>
                            {% for blog in year_hot_blog %}
                                <li><a href="{% url 'blog_detail' blog.id %}">{{ blog.title }}</a></li>
                            {% empty %}
                                <li>暂无热读博文</li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <script>
        {# 图表显示 #}
        var chart = Highcharts.chart('container', {
            chart: {
                type: 'line'
            },
            title: {
                text: null
            },
            xAxis: {
                categories: {{ date_list|safe }}
            },
            yAxis:{
                title:{
                    text: null
                },
                gridLineDashStyle:'Dash',
                labels:{enabled:false}
            },
            plotOptions: {
                line: {
                    dataLabels: {
                        // 开启数据标签
                        enabled: true
                    }
                },
                enableMouseTracking: false,
                // 图例不可点击
                series: {
                    events: {
                        legendItemClick: function(e) {
                            return false; // 直接 return false 即可禁用图例点击事件
                        }
                    }
                }
            },
            series: [{
                name: '阅读量',
                data: {{ read_num_list|safe }}
            }],
            credits:{enabled:false},
            exporting:{enabled:false}
        });
    </script>
{% endblock %}

templates/search.html
{% extends 'blog_list.html' %}
{% load staticfiles %}

{% block title %}
    搜索
{% endblock %}

{% block blog_active %}
    active
{% endblock %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-10 col-md-10 col-lg-10 col-lg-offset-1 col-md-offset-1 col-sm-offset-1">
                {# 博文#}
                <div class="panel panel-default">
                    <div class="panel-heading">搜索到 {{ count }} 篇文章</div>
                    <div class="panel-body">
                        {% for blog in page_obj.object_list %}
                            <div class="blog">
                                <a class="title" href="{% url 'blog_detail' blog.id %}">{{ blog.title }}</a>
                                <p>
                                    {{ blog.content|striptags|truncatechars_html:80 }}
                                </p>
                            </div>
                        {% empty %}
                            <div class="blog">
                                <p>暂未搜索到相关内容，换个关键词继续搜索</p>
                            </div>
                        {% endfor %}
                    </div>
                </div>

                {# 分页 #}
                <nav aria-label="Page navigation">
                    <ul class="pager">
                        {% if page_obj.has_previous %}
                            <li>
                                <a href="?wd={{ search }}&page={{ page_obj.previous_page_number }}">
                                    上一页
                                </a>
                            </li>
                        {% endif %}

                        {% for page in page_list %}
                            {% if page == page_obj.number %}
                                <li><span class="active">{{ page }}</span></li>
                            {% else %}
                                <li><a href="?wd={{ search }}&page={{ page }}">{{ page }}</a></li>
                            {% endif %}
                        {% endfor %}

                        {% if page_obj.has_next %}
                            <li>
                                <a href="?wd={{ search }}&page={{ page_obj.next_page_number }}">
                                    下一页
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
{% endblock %}